export const USER_LOGIN_REQUEST = "USER_LOGIN_ REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";
export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";
export const USER_PROFILE_UPDATE_RESET = "USER_PROFILE_UPDATE_RESET";
export const ALL_USERS_LIST_REQUEST = "ALL_USERS_LIST_REQUEST";
export const ALL_USERS_LIST_SUCCESS = "ALL_USERS_LIST_SUCCESS";
export const ALL_USERS_LIST_FAIL = "ALL_USERS_LIST_FAIL";
export const ALL_USERS_LIST_RESET = "ALL_USERS_LIST_RESET";
export const USER_PROFILE_DELETE_REQUEST = "USER_PROFILE_DELETE_REQUEST";
export const USER_PROFILE_DELETE_SUCCESS = "USER_PROFILE_DELETE_SUCCESS";
export const USER_PROFILE_DELETE_FAIL = "USER_PROFILE_DELETE_FAIL";
export const USER_PROFILE_UPDATEBYADMIN_REQUEST =
  "USER_PROFILE_UPDATEBYADMIN_REQUEST";
export const USER_PROFILE_UPDATEBYADMIN_SUCCESS =
  "USER_ PROFILE _UPDATEBYADMIN_SUCCESS";
export const USER_PROFILE_UPDATEBYADMIN_FAIL =
  "USER_PROFILE_UPDATEBYADMIN_FAIL";
export const USER_PROFILE_UPDATEBYADMIN_RESET =
  "USER_PROFILE_UPDATEBYADMIN_RESET";
